name: Dependabot Auto Merge
description: Automatically merge Dependabot PRs when version comparison is within range

branding:
  color: blue
  icon: git-merge

inputs:
  github-token:
    description: The GitHub token used to merge the pull-request
    required: true

  config:
    description: Path to configuration file (relative to root)
    default: .github/auto-merge.yml
    required: false

runs:
  using: docker
  image: docker://ghcr.io/ahmadnassri/action-dependabot-auto-merge:v2
