name: Dependabot Auto Merge
description: Automatically merge Dependabot PRs when version comparison is within range

branding:
  color: blue
  icon: git-merge

inputs:
  github-token:
    description: The GitHub token used to merge the pull-request
    default: ${{ github.token }}

  command:
    description: The command to pass to Dependabot as a comment
    default: merge

  approve:
    description: Auto-approve pull-requests
    default: true

  target:
    description: The version comparison target (major, minor, patch). This is ignored if .github/auto-merge.yml exists
    default: patch
    required: false

runs:
  using: docker
  image: Dockerfile
